export const GET_VGS = 'GET_VGS'                //* Todos los juegos
export const GET_VG = 'GET_VG'                  //* Un solo juego que coincidan con un nombre
export const GET_VG_BY_ID = 'GET_VG_BY_ID'      //* Un solo juego por id
export const GET_GN = 'GET_GN'                  //* Todos los generos
export const POST_VG = 'POST_VG'                //* Postear un juego
export const FL_DBVG = 'FL_DBVG'                //* Filtro de los juegos creados por el usuario
export const ORD_BYNM = 'ORD_BYNM'              //* ordenado por nombre
export const ORD_BYRT = 'ORD_BYRT'              //* ordenado por rating
export const GET_PT = 'GET_PT'                  //* obtener plataformas desponibles
export const ORD_BYNMBK = 'ORD_BYNMBK'
export const SAVENAME = 'SAVENAME'
export const FLV_BYGNBK = 'FLV_BYGNBK'
export const ORDER_TYPE = 'ORDER_TYPE'
export const PAG_UPDATE = 'PAG_UPDATE'
export const UPDATE_GAME = 'UPDATE_GAME'
export const DELETE_GAME = 'DELETE_GAME'
export const VACIAR_ESTADO = 'VACIAR_ESTADO'