name: Node.js CI/CD  
on:
  push:
    branches: master
  pull_request:
    branches: master
    
defaults:
  run:
   working-directory: ./api
  
   
jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
        
    steps:
    
    - uses: actions/checkout@v4  
    
    - name: Use Node.js ${{ matrix.node-version }}      
      uses: cd api/ && actions/setup-node@v4
      
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
        touch .env 
        echo "${{ secrets.PROD_ENV_FILE }}" > .env
